<div class="row-fluid">
    <div class="span12 well-small well">
        <h4>
            From <input type="date" id="from-date" value="<?php echo date('Y-m-d', time() - (7 * 24 * 60 * 60)); ?>"/>
            to
            <input type="date" id="to-date" value="<?php echo date('Y-m-d'); ?>"/>
            By
            <label class="radio inline">
                <input type="radio" name="interval" id="minutes" value="minutes" checked>
                Minutes
            </label>
            <label class="radio inline">
                <input type="radio" name="interval" id="hours" value="hours" checked="checked">
                Hours
            </label>
            <label class="radio inline">
                <input type="radio" name="interval" id="days" value="days">
                Days
            </label>
        </h4>
    </div>
</div>
<div class="row-fluid">
    <div class="clearfix"></div>
    <div class="span2">
        <div class="btn-group btn-group-vertical pull-right" id="btn-keys">
            <?php foreach ($this->keys as $key): ?>
                <button class="btn" type="button"><?php echo $key['key']; ?></button>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="span9">
        <div id="chart"></div>
    </div>
</div>

<script type="text/javascript">
    google.load("visualization", "1", {packages: ["corechart"]});

    $(document).ready(function () {
        $('#btn-keys > button').click(function () {
            $(this).toggleClass('active btn-success');
            var keys = [];
            $('#btn-keys > button.active').each(function (key, val) {
                keys.push($(val).html());
            });
            if (keys.length === 0) {
                return false;
            }
            var fromDate = $('#from-date').val();
            var toDate = $('#to-date').val();
            var interval = $('input[name=interval]:checked').val();
            getData(fromDate, toDate, interval, keys);
        });
    });

    function getData(fromDate, toDate, interval, keys) {
        var data = {
            fromDate: fromDate,
            toDate: toDate,
            interval: interval,
            keys: keys
        };
        $.post('/fafs-browser/data', data, function (res) {
            graphData(res);
        }, 'json');
    }

    function graphData(data) {
        console.log(data);
        var dataTable = new google.visualization.arrayToDataTable(data);

        console.log(dataTable);
        var chart = new google.visualization.LineChart(document.getElementById('chart'));
        chart.draw(dataTable);
    }
</script>

